[project]
name = "wjdr"
version = "0.1.0"
description = "WJDR is a Python application to help a GM create and manage their RPG campaigns."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "nicegui>=3.1.0",
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "interrogate>=1.7.0",
    "mypy>=1.18.2",
    "pre-commit>=4.5.1",
    "pytest>=8.4.1",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.12.11",
]


# Tools section
[tool.uv.sources]
wjdr = { workspace = true }

[tool.pytest.ini_options]
markers = [
    "unitary", # Unit tests
    "integration", # Integration tests
    "e2e", # End-to-end tests
    "gui" # GUI tests
]

[tool.ruff]
line-length = 240
