[project]
name = "wjdr"
version = "0.1.0"
description = "WJDR is a Python application to help a GM create and manage their RPG campaigns."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "nicegui>=3.1.0",
    "pydantic>=2.11.7",
    "reflex>=0.8.24.post1",
]

[dependency-groups]

hooks = [
    "pre-commit>=4.5.1",
]

lint = [
    "interrogate>=1.7.0",
    "ruff>=0.12.11",
]

test = [
    "pytest>=8.4.1",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
]

dev = [
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "hooks" },
]

# Tools section
[tool.uv.sources]
wjdr = { workspace = true }

[tool.uv]
package = true


[tool.pytest.ini_options]
addopts = ["-ra", "-q"]
markers = [
    "unitary", # Unit tests
    "integration", # Integration tests
    "e2e", # End-to-end tests
    "gui" # GUI tests
]

[tool.ruff]
line-length = 240
# Rules that are selected :
# E : Pycodestyle errors
# F : Pyflakes codes
# W : Pycodestyle warnings
# C90 : McCabe complexity plugin
# B : Bugbear plugin
# B9 : Bugbear plugin (new rules)
# I : Import conventions plugin
# Q000 : Security plugin
lint.select = ["E", "F", "W", "C90", "B", "B9", "I", "Q000"]
# Rules to ignore :
# E501 : line too long (handled by line-length setting)
lint.ignore = ["E501"]
# Exclude docs and test data folders
exclude = ["docs", "tests/data"]

