"""initial schema

Revision ID: 0982b0daff1c
Revises: 
Create Date: 2026-04-27 14:50:47.282158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0982b0daff1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AttributesTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_skill', sa.Integer(), nullable=False),
    sa.Column('ballistic_skill', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('toughness', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('willpower', sa.Integer(), nullable=False),
    sa.Column('fellowship', sa.Integer(), nullable=False),
    sa.Column('attacks', sa.Integer(), nullable=False),
    sa.Column('wounds', sa.Integer(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('insanity_points', sa.Integer(), nullable=False),
    sa.Column('fate_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CapacityTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.Column('category', sa.Enum('TALENT', 'SKILL', name='categoryenum'), nullable=False),
    sa.Column('skill_attribute', sa.Enum('WEAPON_SKILL', 'BALLISTIC_SKILL', 'STRENGTH', 'TOUGHNESS', 'AGILITY', 'INTELLIGENCE', 'WILLPOWER', 'FELLOWSHIP', name='primaryattributeenum'), nullable=True),
    sa.Column('talent_bonus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChapterMarkdownTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CurrencyTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brass_pennies', sa.Integer(), nullable=False),
    sa.Column('silver_shillings', sa.Integer(), nullable=False),
    sa.Column('gold_crowns', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DicePoolTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modifier', sa.Integer(), nullable=False),
    sa.Column('dynamic_modifier', sa.Enum('BE', 'BF', name='dynamicbonusenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DiceTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faces', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MediaTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('MediaTable_name_index', 'MediaTable', ['name'], unique=False)
    op.create_table('PersonalDetailTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biography', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('eye_color', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hair_color', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('siblings_number', sa.Integer(), nullable=True),
    sa.Column('astral_sign', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('birthplace', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SpellCategoryTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WeaponAttributeTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CampaignTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.Column('gm_name', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('illustration_image_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['illustration_image_id'], ['MediaTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('campaignTable_gm_name_index', 'CampaignTable', ['gm_name'], unique=False)
    op.create_index('campaignTable_name_index', 'CampaignTable', ['name'], unique=False)
    op.create_index('campaignTable_start_date_index', 'CampaignTable', ['start_date'], unique=False)
    op.create_table('CareerTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.Column('is_basic', sa.Boolean(), nullable=False),
    sa.Column('special_access_rule', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('attributes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attributes_id'], ['AttributesTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DicePoolDiceLinkTable',
    sa.Column('dice_pool_id', sa.Integer(), nullable=False),
    sa.Column('dices_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dice_pool_id'], ['DicePoolTable.id'], ),
    sa.ForeignKeyConstraint(['dices_id'], ['DiceTable.id'], ),
    sa.PrimaryKeyConstraint('dice_pool_id', 'dices_id')
    )
    op.create_table('ObjectTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.Column('clutter', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Enum('EXCEPTIONAL', 'GOOD', 'NORMAL', 'MEDIOCRE', name='qualityenum'), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('damages_id', sa.Integer(), nullable=True),
    sa.Column('armour_points', sa.Integer(), nullable=True),
    sa.Column('armour_location', sa.Enum('HEAD', 'LEFT_ARM', 'RIGHT_ARM', 'BODY', 'LEFT_LEG', 'RIGHT_LEG', name='locationenum'), nullable=True),
    sa.ForeignKeyConstraint(['damages_id'], ['DiceTable.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['CurrencyTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlayableCharacterTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('gender', sa.Enum('MASCULIN', 'FEMININ', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('race', sa.Enum('DWARF', 'HUMAN', 'ELF', 'HALFLING', name='playableraceenum'), nullable=False),
    sa.Column('current_experience', sa.Integer(), nullable=False),
    sa.Column('total_experience', sa.Integer(), nullable=False),
    sa.Column('personal_details_id', sa.Integer(), nullable=True),
    sa.Column('base_attributes_id', sa.Integer(), nullable=False),
    sa.Column('total_attributes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_attributes_id'], ['AttributesTable.id'], ),
    sa.ForeignKeyConstraint(['personal_details_id'], ['PersonalDetailTable.id'], ),
    sa.ForeignKeyConstraint(['total_attributes_id'], ['AttributesTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SpellTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.Column('is_ritual', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('damage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['SpellCategoryTable.id'], ),
    sa.ForeignKeyConstraint(['damage_id'], ['DicePoolTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CareerCapacityGroupTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Uuid(), nullable=False),
    sa.Column('pick_count', sa.Integer(), nullable=False),
    sa.Column('any_specialization', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['CareerTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CareerCareerLinkTable',
    sa.Column('upstream_career_id', sa.Uuid(), nullable=False),
    sa.Column('downstream_career_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['downstream_career_id'], ['CareerTable.id'], ),
    sa.ForeignKeyConstraint(['upstream_career_id'], ['CareerTable.id'], ),
    sa.PrimaryKeyConstraint('upstream_career_id', 'downstream_career_id')
    )
    op.create_table('CareerEquipmentGroupTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Uuid(), nullable=False),
    sa.Column('pick_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['CareerTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EquipmentTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['ObjectTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlayableCharacterCapacityLinkTable',
    sa.Column('playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('capacity_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Enum('BASE', 'LVL1', 'LVL2', name='skilllevelenum'), nullable=True),
    sa.ForeignKeyConstraint(['capacity_id'], ['CapacityTable.id'], ),
    sa.ForeignKeyConstraint(['playable_character_id'], ['PlayableCharacterTable.id'], ),
    sa.PrimaryKeyConstraint('playable_character_id', 'capacity_id')
    )
    op.create_table('PlayableCharacterCareerLinkTable',
    sa.Column('playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('career_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['CareerTable.id'], ),
    sa.ForeignKeyConstraint(['playable_character_id'], ['PlayableCharacterTable.id'], ),
    sa.PrimaryKeyConstraint('playable_character_id', 'career_id')
    )
    op.create_table('PlayableCharacterSpellLinkTable',
    sa.Column('playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playable_character_id'], ['PlayableCharacterTable.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['SpellTable.id'], ),
    sa.PrimaryKeyConstraint('playable_character_id', 'spell_id')
    )
    op.create_table('ScenarioTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('illustration_image_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['CampaignTable.id'], ),
    sa.ForeignKeyConstraint(['illustration_image_id'], ['MediaTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('scenarioTable_name_index', 'ScenarioTable', ['name'], unique=False)
    op.create_table('WeaponWeaponAttributesLinkTable',
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.Column('weapon_attributes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['weapon_attributes_id'], ['WeaponAttributeTable.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['ObjectTable.id'], ),
    sa.PrimaryKeyConstraint('weapon_id', 'weapon_attributes_id')
    )
    op.create_table('CareerCapacityGroupOptionLinkTable',
    sa.Column('career_capacity_group_id', sa.Integer(), nullable=False),
    sa.Column('capacity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capacity_id'], ['CapacityTable.id'], ),
    sa.ForeignKeyConstraint(['career_capacity_group_id'], ['CareerCapacityGroupTable.id'], ),
    sa.PrimaryKeyConstraint('career_capacity_group_id', 'capacity_id')
    )
    op.create_table('CareerEquipmentGroupOptionLinkTable',
    sa.Column('career_equipment_group_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('fixed_quantity', sa.Integer(), nullable=True),
    sa.Column('random_quantity_dice_pool_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(CASE WHEN fixed_quantity IS NULL THEN 0 ELSE 1 END) + (CASE WHEN random_quantity_dice_pool_id IS NULL THEN 0 ELSE 1 END) = 1', name='career_equipment_quantity_xor_check'),
    sa.ForeignKeyConstraint(['career_equipment_group_id'], ['CareerEquipmentGroupTable.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['EquipmentTable.id'], ),
    sa.ForeignKeyConstraint(['random_quantity_dice_pool_id'], ['DicePoolTable.id'], ),
    sa.PrimaryKeyConstraint('career_equipment_group_id', 'equipment_id')
    )
    op.create_table('ChapterTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('illustration_image_id', sa.Uuid(), nullable=True),
    sa.Column('markdown_content_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['illustration_image_id'], ['MediaTable.id'], ),
    sa.ForeignKeyConstraint(['markdown_content_id'], ['ChapterMarkdownTable.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['ScenarioTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('chapterTable_name_index', 'ChapterTable', ['name'], unique=False)
    op.create_table('PlayableCharacterEquipmentLinkTable',
    sa.Column('playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['EquipmentTable.id'], ),
    sa.ForeignKeyConstraint(['playable_character_id'], ['PlayableCharacterTable.id'], ),
    sa.PrimaryKeyConstraint('playable_character_id', 'equipment_id')
    )
    op.create_table('ChapterMediaLinkTable',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['ChapterTable.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['MediaTable.id'], ),
    sa.PrimaryKeyConstraint('chapter_id', 'media_id')
    )
    op.create_table('NonPlayableCharacterTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('gender', sa.Enum('MASCULIN', 'FEMININ', 'OTHER', name='genderenum'), nullable=True),
    sa.Column('race', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.Column('special_rules', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.Column('difficulty', sa.Enum('VERY_EASY', 'MEDIUM_EASY', 'EASY', 'AVERAGE', 'HARD', 'MEDIUM_HARD', 'VERY_HARD', 'IMPOSSIBLE', name='difficultyenum'), nullable=True),
    sa.Column('attributes_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attributes_id'], ['AttributesTable.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['ChapterTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NonPlayableCharacterCapacityLinkTable',
    sa.Column('non_playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('capacity_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Enum('BASE', 'LVL1', 'LVL2', name='skilllevelenum'), nullable=True),
    sa.ForeignKeyConstraint(['capacity_id'], ['CapacityTable.id'], ),
    sa.ForeignKeyConstraint(['non_playable_character_id'], ['NonPlayableCharacterTable.id'], ),
    sa.PrimaryKeyConstraint('non_playable_character_id', 'capacity_id')
    )
    op.create_table('NonPlayableCharacterSpellLinkTable',
    sa.Column('non_playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['non_playable_character_id'], ['NonPlayableCharacterTable.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['SpellTable.id'], ),
    sa.PrimaryKeyConstraint('non_playable_character_id', 'spell_id')
    )
    op.create_table('NonPlayableCharacterSpoilLinkTable',
    sa.Column('non_playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('fixed_quantity', sa.Integer(), nullable=True),
    sa.Column('random_quantity_dice_pool_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(CASE WHEN fixed_quantity IS NULL THEN 0 ELSE 1 END) + (CASE WHEN random_quantity_dice_pool_id IS NULL THEN 0 ELSE 1 END) = 1', name='npc_spoil_quantity_xor_check'),
    sa.ForeignKeyConstraint(['equipment_id'], ['EquipmentTable.id'], ),
    sa.ForeignKeyConstraint(['non_playable_character_id'], ['NonPlayableCharacterTable.id'], ),
    sa.ForeignKeyConstraint(['random_quantity_dice_pool_id'], ['DicePoolTable.id'], ),
    sa.PrimaryKeyConstraint('non_playable_character_id', 'equipment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NonPlayableCharacterSpoilLinkTable')
    op.drop_table('NonPlayableCharacterSpellLinkTable')
    op.drop_table('NonPlayableCharacterCapacityLinkTable')
    op.drop_table('NonPlayableCharacterTable')
    op.drop_table('ChapterMediaLinkTable')
    op.drop_table('PlayableCharacterEquipmentLinkTable')
    op.drop_index('chapterTable_name_index', table_name='ChapterTable')
    op.drop_table('ChapterTable')
    op.drop_table('CareerEquipmentGroupOptionLinkTable')
    op.drop_table('CareerCapacityGroupOptionLinkTable')
    op.drop_table('WeaponWeaponAttributesLinkTable')
    op.drop_index('scenarioTable_name_index', table_name='ScenarioTable')
    op.drop_table('ScenarioTable')
    op.drop_table('PlayableCharacterSpellLinkTable')
    op.drop_table('PlayableCharacterCareerLinkTable')
    op.drop_table('PlayableCharacterCapacityLinkTable')
    op.drop_table('EquipmentTable')
    op.drop_table('CareerEquipmentGroupTable')
    op.drop_table('CareerCareerLinkTable')
    op.drop_table('CareerCapacityGroupTable')
    op.drop_table('SpellTable')
    op.drop_table('PlayableCharacterTable')
    op.drop_table('ObjectTable')
    op.drop_table('DicePoolDiceLinkTable')
    op.drop_table('CareerTable')
    op.drop_index('campaignTable_start_date_index', table_name='CampaignTable')
    op.drop_index('campaignTable_name_index', table_name='CampaignTable')
    op.drop_index('campaignTable_gm_name_index', table_name='CampaignTable')
    op.drop_table('CampaignTable')
    op.drop_table('WeaponAttributeTable')
    op.drop_table('SpellCategoryTable')
    op.drop_table('PersonalDetailTable')
    op.drop_index('MediaTable_name_index', table_name='MediaTable')
    op.drop_table('MediaTable')
    op.drop_table('DiceTable')
    op.drop_table('DicePoolTable')
    op.drop_table('CurrencyTable')
    op.drop_table('ChapterMarkdownTable')
    op.drop_table('CapacityTable')
    op.drop_table('AttributesTable')
    # ### end Alembic commands ###
