"""Add scenario and chapter equipment reward groups

Revision ID: 2da184808cd9
Revises: b900bc8f729c
Create Date: 2026-04-27 21:28:11.033510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da184808cd9'
down_revision: Union[str, Sequence[str], None] = 'b900bc8f729c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ScenarioRewardGroupTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('pick_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['ScenarioTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChapterRewardGroupTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('pick_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['ChapterTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ScenarioRewardGroupOptionLinkTable',
    sa.Column('scenario_reward_group_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('fixed_quantity', sa.Integer(), nullable=True),
    sa.Column('random_quantity_dice_pool_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(CASE WHEN fixed_quantity IS NULL THEN 0 ELSE 1 END) + (CASE WHEN random_quantity_dice_pool_id IS NULL THEN 0 ELSE 1 END) = 1', name='scenario_reward_quantity_xor_check'),
    sa.ForeignKeyConstraint(['equipment_id'], ['EquipmentTable.id'], ),
    sa.ForeignKeyConstraint(['random_quantity_dice_pool_id'], ['DicePoolTable.id'], ),
    sa.ForeignKeyConstraint(['scenario_reward_group_id'], ['ScenarioRewardGroupTable.id'], ),
    sa.PrimaryKeyConstraint('scenario_reward_group_id', 'equipment_id')
    )
    op.create_table('ChapterRewardGroupOptionLinkTable',
    sa.Column('chapter_reward_group_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('fixed_quantity', sa.Integer(), nullable=True),
    sa.Column('random_quantity_dice_pool_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(CASE WHEN fixed_quantity IS NULL THEN 0 ELSE 1 END) + (CASE WHEN random_quantity_dice_pool_id IS NULL THEN 0 ELSE 1 END) = 1', name='chapter_reward_quantity_xor_check'),
    sa.ForeignKeyConstraint(['chapter_reward_group_id'], ['ChapterRewardGroupTable.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['EquipmentTable.id'], ),
    sa.ForeignKeyConstraint(['random_quantity_dice_pool_id'], ['DicePoolTable.id'], ),
    sa.PrimaryKeyConstraint('chapter_reward_group_id', 'equipment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ChapterRewardGroupOptionLinkTable')
    op.drop_table('ScenarioRewardGroupOptionLinkTable')
    op.drop_table('ChapterRewardGroupTable')
    op.drop_table('ScenarioRewardGroupTable')
    # ### end Alembic commands ###
