"""Add unique playable character career order

Revision ID: 424b076d6486
Revises: 87995291b33b
Create Date: 2026-04-27 19:00:11.696912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424b076d6486'
down_revision: Union[str, Sequence[str], None] = '87995291b33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('playable_character_career_order_unique', 'PlayableCharacterCareerLinkTable', ['playable_character_id', 'order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playable_character_career_order_unique', 'PlayableCharacterCareerLinkTable', type_='unique')
    # ### end Alembic commands ###
