"""Add mental illness many-to-many to playable and non-playable characters

Revision ID: 781ee757ac82
Revises: 97e3fce6c941
Create Date: 2026-04-27 16:33:39.816027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '781ee757ac82'
down_revision: Union[str, Sequence[str], None] = '97e3fce6c941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MentalIllnessTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlayableCharacterMentalIllnessLinkTable',
    sa.Column('playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('mental_illness_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mental_illness_id'], ['MentalIllnessTable.id'], ),
    sa.ForeignKeyConstraint(['playable_character_id'], ['PlayableCharacterTable.id'], ),
    sa.PrimaryKeyConstraint('playable_character_id', 'mental_illness_id')
    )
    op.create_table('NonPlayableCharacterMentalIllnessLinkTable',
    sa.Column('non_playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('mental_illness_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mental_illness_id'], ['MentalIllnessTable.id'], ),
    sa.ForeignKeyConstraint(['non_playable_character_id'], ['NonPlayableCharacterTable.id'], ),
    sa.PrimaryKeyConstraint('non_playable_character_id', 'mental_illness_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NonPlayableCharacterMentalIllnessLinkTable')
    op.drop_table('PlayableCharacterMentalIllnessLinkTable')
    op.drop_table('MentalIllnessTable')
    # ### end Alembic commands ###
