"""Add playable character campaign many-to-many

Revision ID: b900bc8f729c
Revises: 424b076d6486
Create Date: 2026-04-27 19:58:11.349664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b900bc8f729c'
down_revision: Union[str, Sequence[str], None] = '424b076d6486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PlayableCharacterCampaignLinkTable',
    sa.Column('playable_character_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['CampaignTable.id'], ),
    sa.ForeignKeyConstraint(['playable_character_id'], ['PlayableCharacterTable.id'], ),
    sa.PrimaryKeyConstraint('playable_character_id', 'campaign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlayableCharacterCampaignLinkTable')
    # ### end Alembic commands ###
